// app/terms/page.tsx
import Link from "next/link";
import PageTitle from "@/components/ui/PageTitle";

export const metadata = {
  title: "Terms & Conditions - Mocki AI",
  description:
    "The terms for using Mocki AI, a free voice-based mock interview practice tool.",
};

export default function TermsPage() {
  return (
    <>
      {/* Page Title */}
      <PageTitle
        title="Terms & Conditions"
        subtitle="The simple rules for using Mocki AI."
      />
      <section className="term-wrap font-dm lg:pb-24 pb-12">
        <div className="max-w-screen-xl mx-auto px-3 sm:px-6 md:px-14 lg:px-14 xl:px-18 2xl:px-3 lg:pt-24 pt-20">
          <div className="lg:w-7/12 mx-auto">
            {/* 1. What Mocki AI Is */}
            <h2 className="text-2xl md:text-3xl text-gray-900 font-semibold">
              1. What Mocki AI Is
            </h2>
            <p className="text-gray-800 font-medium text-[17px] leading-7 py-6">
              Mocki AI is a free, personal project that lets you practice job
              interviews by speaking your answers out loud and getting
              AI-generated feedback. It is not a company, and there is no
              paid plan — by using this site, you agree to the terms below.
            </p>

            {/* 2. Your Account */}
            <h2 className="text-2xl md:text-3xl text-gray-900 font-semibold mt-10">
              2. Your Account
            </h2>
            <ul className="list-disc py-6 pl-5 mb-3 text-gray-800 font-medium text-[17px] leading-7">
              <li>
                Signing in is handled by Clerk, a third-party authentication
                provider — Mocki AI never sees or stores your password.
              </li>
              <li>
                You&apos;re responsible for keeping your account access
                secure, and for the accuracy of the CV and information you
                upload.
              </li>
              <li>
                You can stop using the service and ask for your account and
                data to be deleted at any time (see{" "}
                <Link href="/contact" className="text-blue-600 underline">
                  Contact
                </Link>
                ).
              </li>
            </ul>

            {/* 3. Your CV & Interview Data */}
            <h2 className="text-2xl md:text-3xl text-gray-900 font-semibold mb-4 mt-10">
              3. Your CV & Interview Data
            </h2>
            <p className="text-gray-800 font-medium text-[17px] leading-7">
              When you upload a CV, it&apos;s processed by an AI model to
              extract your profile (skills, experience, etc.) so interview
              questions can be tailored to you. Your completed interviews —
              questions, transcribed answers, and the resulting report — are
              saved to your account so you can revisit them in History.
            </p>
            <p className="text-gray-800 font-medium text-[17px] leading-7 mt-4">
              This data is used only to run the product for you. It is not
              sold, and it is not shared with third parties beyond the
              service providers needed to run the app itself (authentication,
              hosting, and the AI model used for scoring).
            </p>

            {/* 4. AI-Generated Content */}
            <h2 className="text-2xl md:text-3xl text-gray-900 font-semibold mb-4 mt-10">
              4. AI-Generated Content
            </h2>
            <p className="text-gray-800 font-medium text-[17px] leading-7">
              Interview questions, scores, and feedback are generated by an
              AI model based on the text of your spoken answers. They are
              meant as practice guidance, not a guaranteed or professional
              assessment of your interview readiness — treat your report as
              a helpful estimate, not a certified evaluation.
            </p>
            <p className="text-gray-800 font-medium text-[17px] leading-7 mt-4">
              Camera and microphone access are used only to record your
              answer during a session; Mocki AI does not perform real facial
              or vocal analysis — the &quot;confidence&quot; breakdown in your
              report is derived from your answer text, not from analyzing
              the video or audio itself.
            </p>

            {/* 5. Acceptable Use */}
            <h2 className="text-2xl md:text-3xl text-gray-900 font-semibold mb-4 mt-10">
              5. Acceptable Use
            </h2>
            <ul className="list-disc py-6 pl-5 mb-3 text-gray-800 font-medium text-[17px] leading-7">
              <li>Use the product for its intended purpose: practicing interviews.</li>
              <li>
                Don&apos;t try to disrupt, overload, or reverse-engineer the
                service, or attempt to access another user&apos;s account or
                data.
              </li>
              <li>
                Don&apos;t upload a CV or content that isn&apos;t yours, or
                that contains anything unlawful or harmful.
              </li>
            </ul>

            {/* 6. No Guarantees */}
            <h2 className="text-2xl md:text-3xl text-gray-900 font-semibold mb-4 mt-10">
              6. No Guarantees
            </h2>
            <p className="text-gray-800 font-medium text-[17px] leading-7">
              Mocki AI is provided &quot;as is,&quot; free of charge, and
              maintained by one person in their spare time. There&apos;s no
              uptime guarantee, no support SLA, and no warranty that the
              service will always be available or error-free. Please don&apos;t
              rely on it as your only interview preparation.
            </p>

            {/* 7. Changes to These Terms */}
            <h2 className="text-2xl md:text-3xl text-gray-900 font-semibold mb-4 mt-10">
              7. Changes to These Terms
            </h2>
            <p className="text-gray-800 font-medium text-[17px] leading-7">
              These terms may be updated as the project changes. Continued
              use of Mocki AI after an update means you accept the revised
              terms.
            </p>

            {/* 8. Contact */}
            <h2 className="text-2xl md:text-3xl text-gray-900 font-semibold mb-4 mt-10">
              8. Contact
            </h2>
            <p className="text-gray-800 font-medium text-[17px] leading-7">
              Questions about these terms, or want your data removed? Reach
              out via the{" "}
              <Link href="/contact" className="text-blue-600 underline">
                Contact page
              </Link>
              .
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
